### PR TITLE
fix to have beges export in excel only if the export is selected for …

### LINKED ISSUE #302: ETQ utilisateur, je peux exporter les tableaux présent sur la page résultat
## Contexte
Les utilisateurs ont besoin d'exporter sous format excel les résultats de leur BC (pour les partager, pour les retravailler...)
En haut de la page résultat, j'ai donc une icone qui me permet de télécharger les tableaux présent sur cette page. 

## Tests d'acceptance
Quand je clique sur le bouton pour télécharger les tableaux présent sur la page résultat je télécharge un excel avec : 
- un onglet par export
- Plusieurs tableaux sur chaque onglet les uns en dessous des autress : le premier tableau concerne tous les sites, puis un tableau par site 

Les colonnes/lignes sont exactement les mêmes que sur les tableaux présents sur el site. (on affiche même ce qui est caché)

## Infos de test

Comment bien tester ce ticket ?

## Stratégie technique

Quelle strat technique adopter pour ce ticket ?

### PR DESCRIPTION
**Pull request by cmolle**
…the study

fix #302

### CODE REVIEW

File: src/services/study.ts [hunk 1]
```diff
@@ -431,9 +431,11 @@ export const downloadStudyResults = async (
 
   data.push(formatConsolidatedStudyResultsForExport(study, siteList, tStudy, tExport, tPost, tQuality))
 
-  data.push(
-    formatBegesStudyResultsForExport(study, rules, emissionFactorsWithParts, siteList, tExport, tQuality, tBeges),
-  )
+  if (study.exports.find((exp) => exp.type === Export.Beges)) {
```
Comment (desoindx) [inline src/services/study.ts:434]: nitpick: 
```suggestion
  if (study.exports.some((exp) => exp.type === Export.Beges)) {
```

**Review by desoindx — APPROVED** [review]
